### ISSUE TITLE
ToDo's collection

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/SSB-Tournament-Manager#1]
ToDo's:
- [ ] Kontakte => pers. Daten der Admins?
- [ ] Mehr Konfig-Möglichkeiten bei einem Turnier (z.B. tournament_type, hold_third_place_match, allow_participant_match_reporting, game_name)
- [ ] Super Admin?
- [ ] Landingpage für zukünftige User
- [ ] Datenschutzerklärung?
- [ ] Player -> Guthaben?
- [ ] Rules & Infos aufteilen? -> (General, SSBU, Clublokal, Infos)
- [ ] Feedback & Questions aufteilen?
- [ ] Styling analog https://swisssmash.ch/
- [ ] Discord Infos
- [ ] Datenschutzerklärung
- [ ] Verschiedene Rankings? -> (Stadt, Gesammt Schweiz, Skill)
- [ ] Kalender
